version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    restart: unless-stopped

  notion-connector:
    build: ./notion-connector
    container_name: notion-connector
    ports:
      - "8000:8000"
    environment:
      - NOTION_API_KEY=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
      - MODEL_NAME=openhermes
    depends_on:
      - ollama
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:v1.13.3
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  notion-sync:
    build:
      context: .
      dockerfile: notion-sync/Dockerfile
    image: notion-sync
    container_name: notion-sync
    environment:
      - NOTION_API_KEY=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
    depends_on:
      - qdrant
    restart: "no"  # Ne tourne que lorsqu’on le lance avec docker run

  notion-webhook:
    build: ./notion-webhook
    container_name: notion-webhook
    ports:
      - "8050:8050"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shared:/app/shared
    environment:
      - NOTION_API_KEY=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
      - REDIS_URL=redis://redis:6379
      - QUEUE_NAME=notion_events
      - MAPPING_DB=/app/shared/mapping.db
    depends_on:
      - redis
    restart: unless-stopped

  notion-worker:
    build: ./notion-worker
    container_name: notion-worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shared:/app/shared
    environment:
      - NOTION_API_KEY=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
      - REDIS_URL=redis://redis:6379
      - QUEUE_NAME=notion_events
      - SYNC_IMAGE=notion-sync
      - DOCKER_NETWORK=open-webui-0520_default
    depends_on:
      - redis
      - qdrant
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    command: >
      http --log stdout --log-format=logfmt --authtoken 2v85SFxBruWeXZxVHFcYKPuQ8go_5pzASVKCDQ98ewwNTVTc1 notion-webhook:8050
    depends_on:
      - notion-webhook
    restart: unless-stopped

  api-routing:
    build: ./api-routing
    container_name: api-routing
    ports:
      - "8070:8070"
    restart: unless-stopped


volumes:
  ollama: {}
  open-webui: {}
  qdrant_data: {}
